spring:
  application:
    name: Jd-Auto-Task
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://zyl001:3306/Jd_Auto_Task
    hikari:
      max-lifetime: 1000
      maximum-pool-size: 10


server:
  port: 8080

